name: iot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_animate: ^4.5.2
  qr_flutter: ^4.1.0
  supabase_flutter: ^2.8.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/robo.jpg
    - assets/images/google.png
